[libraries]
slf4jApi = "org.slf4j:slf4j-api:1.7.32"
junit = "junit:junit:4.8.2"
guava = "com.google.guava:guava:20.0"
jsr305 = "com.google.code.findbugs:jsr305:1.3.9"
servletApi = "org.apache.tomcat:tomcat-servlet-api:7.0.8"
freemarker = "org.freemarker:freemarker:2.3.16"
easymock = "org.easymock:easymock:4.1"
commonsLang = "commons-lang:commons-lang:2.6"
hamcrest = "org.hamcrest:hamcrest-core:2.2"
